# Generated by Django 5.1.3 on 2024-11-09 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebPages',
            new_name='WebPage',
        ),
    ]
